"""Add avatar_url to user_profiles

Revision ID: de32520f7dc0
Revises: b2ffddf0cea5
Create Date: 2026-01-16 17:45:30.722678+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de32520f7dc0'
down_revision: Union[str, None] = 'b2ffddf0cea5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade database schema.
    Applica le modifiche al database per portarlo alla versione corrente.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='URL avatar utente (può essere URL esterno o path file caricato)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade database schema.
    Reverte le modifiche per tornare alla versione precedente.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'avatar_url')
    # ### end Alembic commands ###
