"""add missing payment fields

Revision ID: 16ea204871fa
Revises: b1128fd6a7c2
Create Date: 2026-01-18 12:52:02.424980+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16ea204871fa'
down_revision: Union[str, None] = 'b1128fd6a7c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade database schema.
    Applica le modifiche al database per portarlo alla versione corrente.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_login_attempts_success', table_name='login_attempts')
    op.create_index(op.f('ix_login_attempts_success'), 'login_attempts', ['success'], unique=False)
    op.add_column('payments', sa.Column('stripe_client_secret', sa.String(length=500), nullable=True, comment='Stripe client secret per frontend confirmation'))
    op.add_column('payments', sa.Column('transaction_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Dati completi transazione da webhook Stripe'))
    op.add_column('payments', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp pagamento completato (da webhook)'))
    op.add_column('payments', sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp rimborso completato (da webhook)'))
    op.create_index(op.f('ix_payments_paid_at'), 'payments', ['paid_at'], unique=False)
    op.create_index(op.f('ix_payments_refunded_at'), 'payments', ['refunded_at'], unique=False)
    op.drop_index('ix_service_content_service_id', table_name='service_content')
    op.create_index('ix_service_content_service_id', 'service_content', ['service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade database schema.
    Reverte le modifiche per tornare alla versione precedente.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_service_content_service_id', table_name='service_content')
    op.create_index('ix_service_content_service_id', 'service_content', ['service_id'], unique=True)
    op.drop_index(op.f('ix_payments_refunded_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_paid_at'), table_name='payments')
    op.drop_column('payments', 'refunded_at')
    op.drop_column('payments', 'paid_at')
    op.drop_column('payments', 'transaction_data')
    op.drop_column('payments', 'stripe_client_secret')
    op.drop_index(op.f('ix_login_attempts_success'), table_name='login_attempts')
    op.create_index('ix_login_attempts_success', 'login_attempts', ['success', 'attempted_at'], unique=False)
    # ### end Alembic commands ###
