"""Initial schema with all models

Revision ID: c960769efce7
Revises: 
Create Date: 2026-01-15 15:17:34.310839+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c960769efce7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade database schema.
    Applica le modifiche al database per portarlo alla versione corrente.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Categorie blog'
    )
    op.create_index(op.f('ix_blog_categories_slug'), 'blog_categories', ['slug'], unique=True)
    op.create_table('blog_tags',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Tag blog'
    )
    op.create_index(op.f('ix_blog_tags_slug'), 'blog_tags', ['slug'], unique=True)
    op.create_table('services',
    sa.Column('slug', sa.String(length=255), nullable=False, comment='URL-friendly slug (es: audit-gdpr-completo)'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nome servizio (es: Audit GDPR Completo)'),
    sa.Column('category', sa.Enum('AI_COMPLIANCE', 'CYBERSECURITY_NIS2', 'TOOLKIT_FORMAZIONE', name='servicecategory'), nullable=False, comment='Categoria principale servizio'),
    sa.Column('type', sa.Enum('PACCHETTO_FISSO', 'CUSTOM_QUOTE', 'ABBONAMENTO', name='servicetype'), nullable=False, comment='Tipo servizio per workflow acquisto'),
    sa.Column('short_description', sa.Text(), nullable=True, comment='Descrizione breve per listing (max 200 char)'),
    sa.Column('long_description', sa.Text(), nullable=True, comment='Descrizione completa (HTML rich text)'),
    sa.Column('pricing_type', sa.Enum('FIXED', 'RANGE', 'CUSTOM', name='pricingtype'), nullable=False, comment='Tipo pricing per visualizzazione'),
    sa.Column('price_min', sa.Numeric(precision=10, scale=2), nullable=True, comment='Prezzo minimo (per RANGE) o fisso (per FIXED) in EUR'),
    sa.Column('price_max', sa.Numeric(precision=10, scale=2), nullable=True, comment='Prezzo massimo (per RANGE) in EUR'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='Valuta (sempre EUR per Italia)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Servizio attivo e visibile'),
    sa.Column('is_featured', sa.Boolean(), nullable=False, comment='Servizio in evidenza (homepage)'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='Ordinamento per listing (ASC)'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp pubblicazione (NULL = bozza)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.PrimaryKeyConstraint('id'),
    comment='Servizi consulenza vendibili'
    )
    op.create_index(op.f('ix_services_category'), 'services', ['category'], unique=False)
    op.create_index('ix_services_category_active', 'services', ['category', 'is_active'], unique=False)
    op.create_index('ix_services_featured_active', 'services', ['is_featured', 'is_active'], unique=False)
    op.create_index(op.f('ix_services_is_active'), 'services', ['is_active'], unique=False)
    op.create_index(op.f('ix_services_is_featured'), 'services', ['is_featured'], unique=False)
    op.create_index('ix_services_published', 'services', ['published_at'], unique=False)
    op.create_index(op.f('ix_services_published_at'), 'services', ['published_at'], unique=False)
    op.create_index(op.f('ix_services_slug'), 'services', ['slug'], unique=True)
    op.create_index(op.f('ix_services_type'), 'services', ['type'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email univoca per login'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Password hash con Argon2 (NEVER in chiaro!)'),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'EDITOR', 'SUPPORT', 'CUSTOMER', 'GUEST', name='userrole'), nullable=False, comment='Ruolo RBAC per controllo accessi'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Account attivo (False = sospeso)'),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False, comment='Email verificata (richiesto per login)'),
    sa.Column('email_verification_token', sa.String(length=255), nullable=True, comment='Token verifica email (time-limited)'),
    sa.Column('email_verification_expires', sa.DateTime(timezone=True), nullable=True, comment='Scadenza token verifica email'),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False, comment='MFA TOTP abilitato'),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True, comment='Secret TOTP per MFA (encrypted in production)'),
    sa.Column('backup_codes', postgresql.ARRAY(sa.String()), nullable=True, comment='Backup codes per recovery MFA (hashed)'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='Timestamp ultimo login successo'),
    sa.Column('last_login_ip', postgresql.INET(), nullable=True, comment='IP ultimo login successo'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.PrimaryKeyConstraint('id'),
    comment='Tabella utenti con autenticazione e MFA'
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_email_verification_token'), 'users', ['email_verification_token'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_email_verified'), 'users', ['is_email_verified'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index('ix_users_role_active', 'users', ['role', 'is_active'], unique=False)
    op.create_table('ai_guardrails_config',
    sa.Column('config_key', sa.String(length=100), nullable=False, comment='Chiave configurazione'),
    sa.Column('config_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Valore configurazione (JSON)'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Configurazione guardrail AI chatbot'
    )
    op.create_index(op.f('ix_ai_guardrails_config_config_key'), 'ai_guardrails_config', ['config_key'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('LOGIN', 'LOGOUT', 'CREATE', 'READ', 'UPDATE', 'DELETE', 'EXPORT', 'IMPORT', name='auditaction'), nullable=False, comment='Tipo azione eseguita'),
    sa.Column('entity_type', sa.String(length=50), nullable=True, comment='orders, users, invoices, etc.'),
    sa.Column('entity_id', sa.UUID(), nullable=True, comment='ID entità modificata'),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Before/After values JSON'),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Audit trail azioni utenti'
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_action_created', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index('ix_audit_logs_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('blog_posts',
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False, comment='HTML da rich text editor'),
    sa.Column('featured_image', sa.String(length=500), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='contentstatus'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_publish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('seo_title', sa.String(length=255), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['blog_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Post blog'
    )
    op.create_index(op.f('ix_blog_posts_author_id'), 'blog_posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_blog_posts_category_id'), 'blog_posts', ['category_id'], unique=False)
    op.create_index('ix_blog_posts_published', 'blog_posts', ['status', 'published_at'], unique=False)
    op.create_index(op.f('ix_blog_posts_published_at'), 'blog_posts', ['published_at'], unique=False)
    op.create_index(op.f('ix_blog_posts_scheduled_publish_at'), 'blog_posts', ['scheduled_publish_at'], unique=False)
    op.create_index(op.f('ix_blog_posts_slug'), 'blog_posts', ['slug'], unique=True)
    op.create_index(op.f('ix_blog_posts_status'), 'blog_posts', ['status'], unique=False)
    op.create_table('chat_conversations',
    sa.Column('user_id', sa.UUID(), nullable=True, comment='NULL per guest'),
    sa.Column('session_id', sa.String(length=255), nullable=False, comment='Browser session tracking'),
    sa.Column('total_messages', sa.Integer(), nullable=False),
    sa.Column('user_feedback', sa.Enum('THUMBS_UP', 'THUMBS_DOWN', 'NONE', name='userfeedback'), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Conversazioni chatbot AI'
    )
    op.create_index(op.f('ix_chat_conversations_session_id'), 'chat_conversations', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_conversations_user_id'), 'chat_conversations', ['user_id'], unique=False)
    op.create_index('ix_chat_conversations_user_session', 'chat_conversations', ['user_id', 'session_id'], unique=False)
    op.create_table('email_campaigns',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nome interno campagna'),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('from_name', sa.String(length=255), nullable=False),
    sa.Column('from_email', sa.String(length=255), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'SENDING', 'SENT', 'FAILED', name='campaignstatus'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_recipients', sa.Integer(), nullable=False),
    sa.Column('total_sent', sa.Integer(), nullable=False),
    sa.Column('total_opened', sa.Integer(), nullable=False),
    sa.Column('total_clicked', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Campagne email newsletter'
    )
    op.create_index(op.f('ix_email_campaigns_status'), 'email_campaigns', ['status'], unique=False)
    op.create_table('knowledge_base_documents',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False, comment='pdf, docx, txt, md'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='Size in bytes'),
    sa.Column('content_text', sa.Text(), nullable=True, comment='Estratto plain text'),
    sa.Column('topic', sa.Enum('AI', 'GDPR', 'NIS2', 'CYBERSECURITY', 'GENERAL', name='knowledgetopic'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Documenti knowledge base per RAG'
    )
    op.create_index('ix_knowledge_base_docs_topic_active', 'knowledge_base_documents', ['topic', 'is_active'], unique=False)
    op.create_index(op.f('ix_knowledge_base_documents_is_active'), 'knowledge_base_documents', ['is_active'], unique=False)
    op.create_index(op.f('ix_knowledge_base_documents_topic'), 'knowledge_base_documents', ['topic'], unique=False)
    op.create_table('login_attempts',
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email tentativo login'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='FK a users (NULL se utente non esiste)'),
    sa.Column('success', sa.Boolean(), nullable=False, comment='Login riuscito (True) o fallito (False)'),
    sa.Column('failure_reason', sa.String(length=100), nullable=True, comment='Motivo fallimento (invalid_password, email_not_verified, etc.)'),
    sa.Column('ip_address', postgresql.INET(), nullable=False, comment='IP address tentativo'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='User agent browser/device'),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp tentativo'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Log tentativi login per security'
    )
    op.create_index(op.f('ix_login_attempts_attempted_at'), 'login_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_email'), 'login_attempts', ['email'], unique=False)
    op.create_index('ix_login_attempts_email_timestamp', 'login_attempts', ['email', 'attempted_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_ip_address'), 'login_attempts', ['ip_address'], unique=False)
    op.create_index('ix_login_attempts_ip_timestamp', 'login_attempts', ['ip_address', 'attempted_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_success'), 'login_attempts', ['success'], unique=False)
    op.create_index(op.f('ix_login_attempts_user_id'), 'login_attempts', ['user_id'], unique=False)
    op.create_table('media_library',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='Size in bytes'),
    sa.Column('width', sa.Integer(), nullable=True, comment='Per immagini'),
    sa.Column('height', sa.Integer(), nullable=True, comment='Per immagini'),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('folder', sa.String(length=255), nullable=False, comment='Organizzazione virtuale'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Media library per upload files'
    )
    op.create_index('ix_media_library_folder', 'media_library', ['folder'], unique=False)
    op.create_index('ix_media_library_mime', 'media_library', ['mime_type'], unique=False)
    op.create_index(op.f('ix_media_library_uploaded_by'), 'media_library', ['uploaded_by'], unique=False)
    op.create_table('newsletter_subscribers',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'UNSUBSCRIBED', 'BOUNCED', name='subscriberstatus'), nullable=False),
    sa.Column('subscribed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True, comment='web_form, manual, import'),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('confirmation_token', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Iscritti newsletter'
    )
    op.create_index(op.f('ix_newsletter_subscribers_confirmation_token'), 'newsletter_subscribers', ['confirmation_token'], unique=True)
    op.create_index(op.f('ix_newsletter_subscribers_email'), 'newsletter_subscribers', ['email'], unique=True)
    op.create_index(op.f('ix_newsletter_subscribers_status'), 'newsletter_subscribers', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False, comment='order_update, invoice_ready, ticket_reply, blog_new, etc.'),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('action_url', sa.String(length=500), nullable=True, comment='URL per azione (es: /orders/123)'),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Notifiche in-app utenti'
    )
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('pages',
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('page_type', sa.Enum('HOMEPAGE', 'SERVICE', 'ABOUT', 'CONTACT', 'CUSTOM', name='pagetype'), nullable=False),
    sa.Column('content_blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array blocchi content JSON'),
    sa.Column('seo_title', sa.String(length=255), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('seo_keywords', sa.Text(), nullable=True),
    sa.Column('og_image', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='contentstatus'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Pagine CMS'
    )
    op.create_index(op.f('ix_pages_page_type'), 'pages', ['page_type'], unique=False)
    op.create_index(op.f('ix_pages_published_at'), 'pages', ['published_at'], unique=False)
    op.create_index(op.f('ix_pages_slug'), 'pages', ['slug'], unique=True)
    op.create_index(op.f('ix_pages_status'), 'pages', ['status'], unique=False)
    op.create_index('ix_pages_status_published', 'pages', ['status', 'published_at'], unique=False)
    op.create_table('quote_requests',
    sa.Column('request_number', sa.String(length=50), nullable=False, comment='Numero richiesta (es: QR-2026-00001)'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='FK a users (nullable per guest)'),
    sa.Column('service_id', sa.UUID(), nullable=False, comment='FK a services'),
    sa.Column('contact_name', sa.String(length=255), nullable=False, comment='Nome contatto'),
    sa.Column('contact_email', sa.String(length=255), nullable=False, comment='Email contatto'),
    sa.Column('contact_phone', sa.String(length=20), nullable=True, comment='Telefono contatto'),
    sa.Column('company_name', sa.String(length=255), nullable=True, comment='Azienda (opzionale)'),
    sa.Column('message', sa.Text(), nullable=True, comment='Messaggio/descrizione esigenze'),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Risposte questionario custom (JSON key-value)'),
    sa.Column('status', sa.Enum('NEW', 'IN_REVIEW', 'QUOTED', 'ACCEPTED', 'REJECTED', name='quoterequeststatus'), nullable=False, comment='Status richiesta'),
    sa.Column('quoted_amount', sa.Numeric(precision=10, scale=2), nullable=True, comment='Importo preventivo (EUR)'),
    sa.Column('quoted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp invio preventivo'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Richieste preventivo personalizzato'
    )
    op.create_index(op.f('ix_quote_requests_contact_email'), 'quote_requests', ['contact_email'], unique=False)
    op.create_index('ix_quote_requests_email', 'quote_requests', ['contact_email'], unique=False)
    op.create_index(op.f('ix_quote_requests_request_number'), 'quote_requests', ['request_number'], unique=True)
    op.create_index(op.f('ix_quote_requests_service_id'), 'quote_requests', ['service_id'], unique=False)
    op.create_index(op.f('ix_quote_requests_status'), 'quote_requests', ['status'], unique=False)
    op.create_index('ix_quote_requests_status_created', 'quote_requests', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_quote_requests_user_id'), 'quote_requests', ['user_id'], unique=False)
    op.create_table('service_content',
    sa.Column('service_id', sa.UUID(), nullable=False, comment='FK a services (one-to-one)'),
    sa.Column('hero_title', sa.String(length=255), nullable=True, comment='Titolo hero (override service.name se presente)'),
    sa.Column('hero_subtitle', sa.Text(), nullable=True, comment='Sottotitolo hero'),
    sa.Column('hero_image_url', sa.String(length=500), nullable=True, comment='URL immagine hero (da media library)'),
    sa.Column('hero_cta_text', sa.String(length=100), nullable=True, comment='Testo CTA primaria (es: Richiedi Preventivo)'),
    sa.Column('hero_cta_url', sa.String(length=500), nullable=True, comment='URL CTA (es: /contatti o #quote-form)'),
    sa.Column('problem_section', sa.Text(), nullable=True, comment="Sezione 'Il Problema' (HTML)"),
    sa.Column('solution_section', sa.Text(), nullable=True, comment="Sezione 'La Soluzione' (HTML)"),
    sa.Column('what_includes', sa.Text(), nullable=True, comment='Cosa include il servizio (HTML bullet list)'),
    sa.Column('for_who_section', sa.Text(), nullable=True, comment='Per chi è questo servizio (HTML)'),
    sa.Column('not_for_who_section', sa.Text(), nullable=True, comment='Per chi NON è questo servizio (HTML)'),
    sa.Column('process_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Step processo (JSON array: [{number, title, description}])'),
    sa.Column('testimonials', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Testimonials (JSON array: [{text, author, company, rating}])'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Contenuti CMS per pagine servizi'
    )
    op.create_index(op.f('ix_service_content_service_id'), 'service_content', ['service_id'], unique=True)
    op.create_table('service_faqs',
    sa.Column('service_id', sa.UUID(), nullable=False, comment='FK a services'),
    sa.Column('question', sa.String(length=500), nullable=False, comment='Domanda FAQ'),
    sa.Column('answer', sa.Text(), nullable=False, comment='Risposta FAQ (HTML rich text)'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='Ordinamento display (ASC)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='FAQ per servizi'
    )
    op.create_index(op.f('ix_service_faqs_service_id'), 'service_faqs', ['service_id'], unique=False)
    op.create_index('ix_service_faqs_service_order', 'service_faqs', ['service_id', 'sort_order'], unique=False)
    op.create_table('service_images',
    sa.Column('service_id', sa.UUID(), nullable=False, comment='FK a services'),
    sa.Column('image_url', sa.String(length=500), nullable=False, comment='URL immagine (da media library o CDN)'),
    sa.Column('alt_text', sa.String(length=255), nullable=True, comment='Testo alternativo per accessibilità e SEO'),
    sa.Column('is_primary', sa.Boolean(), nullable=False, comment='Immagine primaria (featured)'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='Ordinamento gallery (ASC)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Galleria immagini servizi'
    )
    op.create_index('ix_service_images_primary', 'service_images', ['service_id', 'is_primary'], unique=False)
    op.create_index(op.f('ix_service_images_service_id'), 'service_images', ['service_id'], unique=False)
    op.create_index('ix_service_images_service_order', 'service_images', ['service_id', 'sort_order'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='FK a users'),
    sa.Column('access_token', sa.String(length=500), nullable=True, comment='Access token JWT (opzionale, per tracking)'),
    sa.Column('refresh_token', sa.String(length=500), nullable=False, comment='Refresh token JWT (required)'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Scadenza access token'),
    sa.Column('refresh_expires_at', sa.DateTime(timezone=True), nullable=False, comment='Scadenza refresh token'),
    sa.Column('ip_address', postgresql.INET(), nullable=True, comment='IP address sessione'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='User agent browser/device'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Sessioni JWT con access/refresh tokens'
    )
    op.create_index(op.f('ix_sessions_access_token'), 'sessions', ['access_token'], unique=True)
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_refresh_expires_at'), 'sessions', ['refresh_expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_refresh_token'), 'sessions', ['refresh_token'], unique=True)
    op.create_index('ix_sessions_user_expires', 'sessions', ['user_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('site_settings',
    sa.Column('setting_key', sa.String(length=100), nullable=False, comment='Chiave univoca setting (es: site_name, smtp_host, feature_ai_chat_enabled)'),
    sa.Column('setting_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Valore configurazione (JSON flessibile: string, number, boolean, array, object)'),
    sa.Column('setting_type', sa.String(length=50), nullable=False, comment='Tipo dato: string, number, boolean, json, encrypted'),
    sa.Column('description', sa.Text(), nullable=True, comment='Descrizione setting per admin panel'),
    sa.Column('category', sa.String(length=100), nullable=False, comment='Categoria: general, email, payment, ai, security, feature_flags, limits'),
    sa.Column('is_public', sa.Boolean(), nullable=False, comment='Se True, esposto via API pubblica (es: nome sito, logo). Se False, solo admin.'),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False, comment='Se True, il valore è criptato nel DB (es: API keys, SMTP password)'),
    sa.Column('validation_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Regole validazione (es: min, max, regex, enum) per admin UI'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='Ultimo utente che ha modificato il setting'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Configurazione globale sito (database-driven)'
    )
    op.create_index(op.f('ix_site_settings_category'), 'site_settings', ['category'], unique=False)
    op.create_index('ix_site_settings_category_key', 'site_settings', ['category', 'setting_key'], unique=False)
    op.create_index('ix_site_settings_is_public', 'site_settings', ['is_public'], unique=False)
    op.create_index(op.f('ix_site_settings_setting_key'), 'site_settings', ['setting_key'], unique=True)
    op.create_table('support_tickets',
    sa.Column('ticket_number', sa.String(length=50), nullable=False, comment='TKT-2026-00001'),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'WAITING_CUSTOMER', 'RESOLVED', 'CLOSED', name='ticketstatus'), nullable=False),
    sa.Column('priority', sa.Enum('URGENT', 'HIGH', 'MEDIUM', 'LOW', name='ticketpriority'), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_response_at', sa.DateTime(timezone=True), nullable=True, comment='SLA tracking'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Ticket supporto clienti'
    )
    op.create_index('ix_support_tickets_assigned_status', 'support_tickets', ['assigned_to', 'status'], unique=False)
    op.create_index(op.f('ix_support_tickets_assigned_to'), 'support_tickets', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_support_tickets_category'), 'support_tickets', ['category'], unique=False)
    op.create_index(op.f('ix_support_tickets_priority'), 'support_tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_support_tickets_status'), 'support_tickets', ['status'], unique=False)
    op.create_index('ix_support_tickets_status_priority', 'support_tickets', ['status', 'priority'], unique=False)
    op.create_index(op.f('ix_support_tickets_ticket_number'), 'support_tickets', ['ticket_number'], unique=True)
    op.create_index(op.f('ix_support_tickets_user_id'), 'support_tickets', ['user_id'], unique=False)
    op.create_table('system_logs',
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='loglevel'), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False, comment='auth, payment, email, cms, api, etc.'),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Extra metadata'),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Log applicazione sistema'
    )
    op.create_index(op.f('ix_system_logs_created_at'), 'system_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_logs_level'), 'system_logs', ['level'], unique=False)
    op.create_index('ix_system_logs_level_created', 'system_logs', ['level', 'created_at'], unique=False)
    op.create_index(op.f('ix_system_logs_module'), 'system_logs', ['module'], unique=False)
    op.create_index('ix_system_logs_module_created', 'system_logs', ['module', 'created_at'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='FK a users (one-to-one)'),
    sa.Column('first_name', sa.String(length=100), nullable=True, comment='Nome'),
    sa.Column('last_name', sa.String(length=100), nullable=True, comment='Cognome'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Telefono (formato internazionale)'),
    sa.Column('company_name', sa.String(length=255), nullable=True, comment='Ragione sociale (B2B)'),
    sa.Column('vat_number', sa.String(length=20), nullable=True, comment='Partita IVA (formato: ITXXXXXXXXXXX)'),
    sa.Column('fiscal_code', sa.String(length=16), nullable=True, comment='Codice Fiscale italiano'),
    sa.Column('pec_email', sa.String(length=255), nullable=True, comment='Email PEC per fatture elettroniche'),
    sa.Column('sdi_code', sa.String(length=7), nullable=True, comment='Codice SDI destinatario (7 caratteri)'),
    sa.Column('billing_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Indirizzo fatturazione (JSON: street, city, zip, province, country)'),
    sa.Column('language', sa.String(length=5), nullable=False, comment='Lingua preferita (default italiano)'),
    sa.Column('timezone', sa.String(length=50), nullable=False, comment='Timezone preferito'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Profili utente con dati anagrafici e fatturazione'
    )
    op.create_index('ix_user_profiles_company', 'user_profiles', ['company_name'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_index('ix_user_profiles_vat', 'user_profiles', ['vat_number'], unique=False)
    op.create_index(op.f('ix_user_profiles_vat_number'), 'user_profiles', ['vat_number'], unique=False)
    op.create_table('blog_post_tags',
    sa.Column('blog_post_id', sa.UUID(), nullable=False),
    sa.Column('blog_tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['blog_post_id'], ['blog_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blog_tag_id'], ['blog_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blog_post_id', 'blog_tag_id'),
    comment='Relazione blog posts - tags'
    )
    op.create_table('chat_messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('retrieved_chunks', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array chunk IDs usati per RAG'),
    sa.Column('claude_message_id', sa.String(length=255), nullable=True, comment='Message ID da Claude API'),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Messaggi conversazione AI'
    )
    op.create_index('ix_chat_messages_conversation_created', 'chat_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_table('email_sends',
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('subscriber_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('email_to', sa.String(length=255), nullable=False),
    sa.Column('email_type', sa.Enum('TRANSACTIONAL', 'NEWSLETTER', 'NOTIFICATION', name='emailtype'), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'SENDING', 'SENT', 'FAILED', 'BOUNCED', name='emailstatus'), nullable=False),
    sa.Column('ms_graph_message_id', sa.String(length=255), nullable=True, comment='Message ID da MS Graph API'),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp apertura email'),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp click link'),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.ForeignKeyConstraint(['campaign_id'], ['email_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['newsletter_subscribers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Log invii email con tracking'
    )
    op.create_index(op.f('ix_email_sends_campaign_id'), 'email_sends', ['campaign_id'], unique=False)
    op.create_index('ix_email_sends_campaign_status', 'email_sends', ['campaign_id', 'status'], unique=False)
    op.create_index(op.f('ix_email_sends_email_to'), 'email_sends', ['email_to'], unique=False)
    op.create_index(op.f('ix_email_sends_email_type'), 'email_sends', ['email_type'], unique=False)
    op.create_index(op.f('ix_email_sends_status'), 'email_sends', ['status'], unique=False)
    op.create_index('ix_email_sends_status_queued', 'email_sends', ['status', 'queued_at'], unique=False)
    op.create_table('knowledge_base_chunks',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='Indice chunk nel documento'),
    sa.Column('chunk_text', sa.Text(), nullable=False, comment='Testo chunk'),
    # TODO: Uncomment when pgvector is installed
    # sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True, comment='Vector embedding per similarity search'),
    sa.Column('token_count', sa.Integer(), nullable=True, comment='Numero token nel chunk'),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Metadata aggiuntivi (page_number, section, etc.)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_base_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Chunks con embeddings per RAG'
    )
    op.create_index('ix_knowledge_base_chunks_doc_idx', 'knowledge_base_chunks', ['document_id', 'chunk_index'], unique=False)
    op.create_index(op.f('ix_knowledge_base_chunks_document_id'), 'knowledge_base_chunks', ['document_id'], unique=False)
    op.create_table('orders',
    sa.Column('order_number', sa.String(length=50), nullable=False, comment='Numero ordine (es: ORD-2026-00001)'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='FK a users'),
    sa.Column('quote_request_id', sa.UUID(), nullable=True, comment='FK a quote_requests (se da preventivo)'),
    sa.Column('status', sa.Enum('PENDING', 'AWAITING_PAYMENT', 'PAID', 'PROCESSING', 'COMPLETED', 'CANCELLED', 'REFUNDED', name='orderstatus'), nullable=False, comment='Status ordine'),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False, comment='Subtotale (senza IVA) in EUR'),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='Aliquota IVA % (es: 22.00 per IVA 22%)'),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Importo IVA calcolato in EUR'),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False, comment='Totale ordine (subtotal + IVA) in EUR'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='Valuta (sempre EUR per Italia)'),
    sa.Column('billing_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Snapshot dati fatturazione (from UserProfile)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Note aggiuntive (admin o cliente)'),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp pagamento ricevuto'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp completamento ordine'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.ForeignKeyConstraint(['quote_request_id'], ['quote_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Ordini principali'
    )
    op.create_index(op.f('ix_orders_completed_at'), 'orders', ['completed_at'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_paid_at'), 'orders', ['paid_at'], unique=False)
    op.create_index(op.f('ix_orders_quote_request_id'), 'orders', ['quote_request_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index('ix_orders_status_created', 'orders', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_index('ix_orders_user_status', 'orders', ['user_id', 'status'], unique=False)
    op.create_table('page_versions',
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Snapshot completo contenuto'),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Versioni pagine per rollback'
    )
    op.create_index(op.f('ix_page_versions_page_id'), 'page_versions', ['page_id'], unique=False)
    op.create_index('ix_page_versions_page_version', 'page_versions', ['page_id', 'version_number'], unique=True)
    op.create_table('ticket_messages',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False, comment='Note interne admin (non visibili a cliente)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Messaggi conversazione ticket'
    )
    op.create_index('ix_ticket_messages_ticket_created', 'ticket_messages', ['ticket_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ticket_messages_ticket_id'), 'ticket_messages', ['ticket_id'], unique=False)
    op.create_table('invoices',
    sa.Column('invoice_number', sa.String(length=50), nullable=False, comment='Numero fattura completo (es: 2026/00001)'),
    sa.Column('invoice_year', sa.Integer(), nullable=False, comment='Anno fiscale'),
    sa.Column('invoice_progressive', sa.Integer(), nullable=False, comment="Numero progressivo nell'anno"),
    sa.Column('order_id', sa.UUID(), nullable=False, comment='FK a orders (one-to-one, RESTRICT per sicurezza)'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='FK a users (cliente)'),
    sa.Column('issue_date', sa.Date(), nullable=False, comment='Data emissione fattura'),
    sa.Column('due_date', sa.Date(), nullable=True, comment='Data scadenza pagamento (opzionale)'),
    sa.Column('seller_name', sa.String(length=255), nullable=False, comment='Denominazione cedente'),
    sa.Column('seller_vat', sa.String(length=20), nullable=False, comment='Partita IVA cedente'),
    sa.Column('seller_fiscal_code', sa.String(length=16), nullable=True, comment='Codice Fiscale cedente (se diverso da P.IVA)'),
    sa.Column('seller_address', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Indirizzo cedente (JSON)'),
    sa.Column('seller_regime_fiscale', sa.String(length=10), nullable=False, comment='Regime fiscale cedente (es: RF01 per ordinario)'),
    sa.Column('buyer_name', sa.String(length=255), nullable=False, comment='Denominazione cessionario'),
    sa.Column('buyer_vat', sa.String(length=20), nullable=True, comment='Partita IVA cessionario (B2B)'),
    sa.Column('buyer_fiscal_code', sa.String(length=16), nullable=True, comment='Codice Fiscale cessionario (B2C o se P.IVA mancante)'),
    sa.Column('buyer_pec', sa.String(length=255), nullable=True, comment='Email PEC cessionario per ricezione'),
    sa.Column('buyer_sdi_code', sa.String(length=7), nullable=True, comment='Codice SDI destinatario (7 caratteri)'),
    sa.Column('buyer_address', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Indirizzo cessionario (JSON)'),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False, comment='Imponibile totale (senza IVA)'),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='IVA totale'),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False, comment='Totale fattura (imponibile + IVA)'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='Valuta (sempre EUR per Italia)'),
    sa.Column('pdf_url', sa.String(length=500), nullable=True, comment='URL file PDF per cliente'),
    sa.Column('xml_url', sa.String(length=500), nullable=True, comment='URL file XML PA (per SDI)'),
    sa.Column('xml_signed_url', sa.String(length=500), nullable=True, comment='URL file XML firmato digitalmente (opzionale)'),
    sa.Column('sdi_status', sa.Enum('PENDING', 'MC', 'NS', 'RC', 'EC_ACCEPTED', 'EC_REJECTED', name='sdistatus'), nullable=False, comment='Status notifiche SDI'),
    sa.Column('sdi_sent_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp invio a SDI via PEC'),
    sa.Column('sdi_accepted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp accettazione SDI'),
    sa.Column('sdi_rejection_reason', sa.Text(), nullable=True, comment='Motivo rifiuto SDI (se rejected)'),
    sa.Column('pec_sent', sa.Boolean(), nullable=False, comment='Copia cortesia inviata via PEC a cliente'),
    sa.Column('pec_sent_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp invio PEC a cliente'),
    sa.Column('pec_delivery_receipt', sa.Text(), nullable=True, comment='Ricevuta di consegna PEC (base64 o URL)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Fatture elettroniche italiane (XML PA)'
    )
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_invoice_year'), 'invoices', ['invoice_year'], unique=False)
    op.create_index('ix_invoices_issue_date', 'invoices', ['issue_date'], unique=False)
    op.create_index(op.f('ix_invoices_order_id'), 'invoices', ['order_id'], unique=True)
    op.create_index('ix_invoices_sdi_status', 'invoices', ['sdi_status'], unique=False)
    op.create_index(op.f('ix_invoices_user_id'), 'invoices', ['user_id'], unique=False)
    op.create_index('ix_invoices_user_year', 'invoices', ['user_id', 'invoice_year'], unique=False)
    op.create_index('ix_invoices_year_progressive', 'invoices', ['invoice_year', 'invoice_progressive'], unique=True)
    op.create_table('order_items',
    sa.Column('order_id', sa.UUID(), nullable=False, comment='FK a orders'),
    sa.Column('service_id', sa.UUID(), nullable=True, comment='FK a services (nullable se service eliminato)'),
    sa.Column('service_name', sa.String(length=255), nullable=False, comment='Nome servizio (snapshot)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Descrizione servizio (snapshot)'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Quantità (solitamente 1 per servizi)'),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Prezzo unitario (snapshot) in EUR'),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='Aliquota IVA % per questa riga'),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Totale riga (quantity * unit_price + IVA) in EUR'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Righe ordine (servizi acquistati)'
    )
    op.create_index('ix_order_items_order_id', 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_service_id'), 'order_items', ['service_id'], unique=False)
    op.create_table('payments',
    sa.Column('order_id', sa.UUID(), nullable=False, comment='FK a orders (one-to-one)'),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=False, comment='Stripe Payment Intent ID (pi_...)'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Importo pagamento in EUR'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='Valuta (sempre EUR)'),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', 'REFUNDED', 'CANCELLED', name='paymentstatus'), nullable=False, comment='Status pagamento (da Stripe webhook)'),
    sa.Column('payment_method_type', sa.String(length=50), nullable=True, comment='Tipo metodo pagamento (card, sepa_debit, etc.)'),
    sa.Column('failure_reason', sa.Text(), nullable=True, comment='Motivo fallimento pagamento (da Stripe)'),
    sa.Column('payment_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Metadata Stripe e custom'),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp elaborazione pagamento'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Transazioni pagamento Stripe'
    )
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=True)
    op.create_index(op.f('ix_payments_processed_at'), 'payments', ['processed_at'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index('ix_payments_status_processed', 'payments', ['status', 'processed_at'], unique=False)
    op.create_index('ix_payments_stripe_id', 'payments', ['stripe_payment_intent_id'], unique=False)
    op.create_index(op.f('ix_payments_stripe_payment_intent_id'), 'payments', ['stripe_payment_intent_id'], unique=True)
    op.create_table('ticket_attachments',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.ForeignKeyConstraint(['message_id'], ['ticket_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Allegati ticket support'
    )
    op.create_index(op.f('ix_ticket_attachments_ticket_id'), 'ticket_attachments', ['ticket_id'], unique=False)
    op.create_table('credit_notes',
    sa.Column('credit_note_number', sa.String(length=50), nullable=False, comment='Numero nota credito (es: NC-2026-00001)'),
    sa.Column('original_invoice_id', sa.UUID(), nullable=False, comment='FK a invoices (fattura originale)'),
    sa.Column('issue_date', sa.Date(), nullable=False, comment='Data emissione nota credito'),
    sa.Column('reason', sa.Text(), nullable=False, comment='Causale/motivazione nota credito'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Importo nota credito (positivo) in EUR'),
    sa.Column('xml_url', sa.String(length=500), nullable=True, comment='URL file XML PA nota credito'),
    sa.Column('pdf_url', sa.String(length=500), nullable=True, comment='URL file PDF nota credito'),
    sa.Column('sdi_status', sa.Enum('PENDING', 'MC', 'NS', 'RC', 'EC_ACCEPTED', 'EC_REJECTED', name='sdistatus'), nullable=False, comment='Status notifiche SDI'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.ForeignKeyConstraint(['original_invoice_id'], ['invoices.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Note di credito (storno fatture)'
    )
    op.create_index(op.f('ix_credit_notes_credit_note_number'), 'credit_notes', ['credit_note_number'], unique=True)
    op.create_index('ix_credit_notes_invoice_id', 'credit_notes', ['original_invoice_id'], unique=False)
    op.create_index('ix_credit_notes_issue_date', 'credit_notes', ['issue_date'], unique=False)
    op.create_index(op.f('ix_credit_notes_original_invoice_id'), 'credit_notes', ['original_invoice_id'], unique=False)
    op.create_index(op.f('ix_credit_notes_sdi_status'), 'credit_notes', ['sdi_status'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('invoice_id', sa.UUID(), nullable=False, comment='FK a invoices'),
    sa.Column('line_number', sa.Integer(), nullable=False, comment='Numero riga progressivo (per ordinamento)'),
    sa.Column('description', sa.Text(), nullable=False, comment='Descrizione prestazione/servizio'),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False, comment='Quantità (es: 1.00 per servizi)'),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Prezzo unitario (imponibile) in EUR'),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='Aliquota IVA % (es: 22.00)'),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='IVA calcolata per questa riga'),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False, comment='Totale riga (quantity * unit_price + IVA)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Righe fattura'
    )
    op.create_index(op.f('ix_invoice_lines_invoice_id'), 'invoice_lines', ['invoice_id'], unique=False)
    op.create_index('ix_invoice_lines_invoice_line', 'invoice_lines', ['invoice_id', 'line_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade database schema.
    Reverte le modifiche per tornare alla versione precedente.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invoice_lines_invoice_line', table_name='invoice_lines')
    op.drop_index(op.f('ix_invoice_lines_invoice_id'), table_name='invoice_lines')
    op.drop_table('invoice_lines')
    op.drop_index(op.f('ix_credit_notes_sdi_status'), table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_original_invoice_id'), table_name='credit_notes')
    op.drop_index('ix_credit_notes_issue_date', table_name='credit_notes')
    op.drop_index('ix_credit_notes_invoice_id', table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_credit_note_number'), table_name='credit_notes')
    op.drop_table('credit_notes')
    op.drop_index(op.f('ix_ticket_attachments_ticket_id'), table_name='ticket_attachments')
    op.drop_table('ticket_attachments')
    op.drop_index(op.f('ix_payments_stripe_payment_intent_id'), table_name='payments')
    op.drop_index('ix_payments_stripe_id', table_name='payments')
    op.drop_index('ix_payments_status_processed', table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_processed_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_order_items_service_id'), table_name='order_items')
    op.drop_index('ix_order_items_order_id', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_invoices_year_progressive', table_name='invoices')
    op.drop_index('ix_invoices_user_year', table_name='invoices')
    op.drop_index(op.f('ix_invoices_user_id'), table_name='invoices')
    op.drop_index('ix_invoices_sdi_status', table_name='invoices')
    op.drop_index(op.f('ix_invoices_order_id'), table_name='invoices')
    op.drop_index('ix_invoices_issue_date', table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_year'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_ticket_messages_ticket_id'), table_name='ticket_messages')
    op.drop_index('ix_ticket_messages_ticket_created', table_name='ticket_messages')
    op.drop_table('ticket_messages')
    op.drop_index('ix_page_versions_page_version', table_name='page_versions')
    op.drop_index(op.f('ix_page_versions_page_id'), table_name='page_versions')
    op.drop_table('page_versions')
    op.drop_index('ix_orders_user_status', table_name='orders')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index('ix_orders_status_created', table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_quote_request_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_paid_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_completed_at'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_knowledge_base_chunks_document_id'), table_name='knowledge_base_chunks')
    op.drop_index('ix_knowledge_base_chunks_doc_idx', table_name='knowledge_base_chunks')
    op.drop_table('knowledge_base_chunks')
    op.drop_index('ix_email_sends_status_queued', table_name='email_sends')
    op.drop_index(op.f('ix_email_sends_status'), table_name='email_sends')
    op.drop_index(op.f('ix_email_sends_email_type'), table_name='email_sends')
    op.drop_index(op.f('ix_email_sends_email_to'), table_name='email_sends')
    op.drop_index('ix_email_sends_campaign_status', table_name='email_sends')
    op.drop_index(op.f('ix_email_sends_campaign_id'), table_name='email_sends')
    op.drop_table('email_sends')
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_index('ix_chat_messages_conversation_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('blog_post_tags')
    op.drop_index(op.f('ix_user_profiles_vat_number'), table_name='user_profiles')
    op.drop_index('ix_user_profiles_vat', table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index('ix_user_profiles_company', table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index('ix_system_logs_module_created', table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_module'), table_name='system_logs')
    op.drop_index('ix_system_logs_level_created', table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_level'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_created_at'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_support_tickets_user_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_ticket_number'), table_name='support_tickets')
    op.drop_index('ix_support_tickets_status_priority', table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_status'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_priority'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_category'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_assigned_to'), table_name='support_tickets')
    op.drop_index('ix_support_tickets_assigned_status', table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_site_settings_setting_key'), table_name='site_settings')
    op.drop_index('ix_site_settings_is_public', table_name='site_settings')
    op.drop_index('ix_site_settings_category_key', table_name='site_settings')
    op.drop_index(op.f('ix_site_settings_category'), table_name='site_settings')
    op.drop_table('site_settings')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index('ix_sessions_user_expires', table_name='sessions')
    op.drop_index(op.f('ix_sessions_refresh_token'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_refresh_expires_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_access_token'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_service_images_service_order', table_name='service_images')
    op.drop_index(op.f('ix_service_images_service_id'), table_name='service_images')
    op.drop_index('ix_service_images_primary', table_name='service_images')
    op.drop_table('service_images')
    op.drop_index('ix_service_faqs_service_order', table_name='service_faqs')
    op.drop_index(op.f('ix_service_faqs_service_id'), table_name='service_faqs')
    op.drop_table('service_faqs')
    op.drop_index(op.f('ix_service_content_service_id'), table_name='service_content')
    op.drop_table('service_content')
    op.drop_index(op.f('ix_quote_requests_user_id'), table_name='quote_requests')
    op.drop_index('ix_quote_requests_status_created', table_name='quote_requests')
    op.drop_index(op.f('ix_quote_requests_status'), table_name='quote_requests')
    op.drop_index(op.f('ix_quote_requests_service_id'), table_name='quote_requests')
    op.drop_index(op.f('ix_quote_requests_request_number'), table_name='quote_requests')
    op.drop_index('ix_quote_requests_email', table_name='quote_requests')
    op.drop_index(op.f('ix_quote_requests_contact_email'), table_name='quote_requests')
    op.drop_table('quote_requests')
    op.drop_index('ix_pages_status_published', table_name='pages')
    op.drop_index(op.f('ix_pages_status'), table_name='pages')
    op.drop_index(op.f('ix_pages_slug'), table_name='pages')
    op.drop_index(op.f('ix_pages_published_at'), table_name='pages')
    op.drop_index(op.f('ix_pages_page_type'), table_name='pages')
    op.drop_table('pages')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_newsletter_subscribers_status'), table_name='newsletter_subscribers')
    op.drop_index(op.f('ix_newsletter_subscribers_email'), table_name='newsletter_subscribers')
    op.drop_index(op.f('ix_newsletter_subscribers_confirmation_token'), table_name='newsletter_subscribers')
    op.drop_table('newsletter_subscribers')
    op.drop_index(op.f('ix_media_library_uploaded_by'), table_name='media_library')
    op.drop_index('ix_media_library_mime', table_name='media_library')
    op.drop_index('ix_media_library_folder', table_name='media_library')
    op.drop_table('media_library')
    op.drop_index(op.f('ix_login_attempts_user_id'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_success'), table_name='login_attempts')
    op.drop_index('ix_login_attempts_ip_timestamp', table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_ip_address'), table_name='login_attempts')
    op.drop_index('ix_login_attempts_email_timestamp', table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_email'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_attempted_at'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_knowledge_base_documents_topic'), table_name='knowledge_base_documents')
    op.drop_index(op.f('ix_knowledge_base_documents_is_active'), table_name='knowledge_base_documents')
    op.drop_index('ix_knowledge_base_docs_topic_active', table_name='knowledge_base_documents')
    op.drop_table('knowledge_base_documents')
    op.drop_index(op.f('ix_email_campaigns_status'), table_name='email_campaigns')
    op.drop_table('email_campaigns')
    op.drop_index('ix_chat_conversations_user_session', table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_user_id'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_session_id'), table_name='chat_conversations')
    op.drop_table('chat_conversations')
    op.drop_index(op.f('ix_blog_posts_status'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_slug'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_scheduled_publish_at'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_published_at'), table_name='blog_posts')
    op.drop_index('ix_blog_posts_published', table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_category_id'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_author_id'), table_name='blog_posts')
    op.drop_table('blog_posts')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_ai_guardrails_config_config_key'), table_name='ai_guardrails_config')
    op.drop_table('ai_guardrails_config')
    op.drop_index('ix_users_role_active', table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_email_verified'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email_verification_token'), table_name='users')
    op.drop_index('ix_users_email_active', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_services_type'), table_name='services')
    op.drop_index(op.f('ix_services_slug'), table_name='services')
    op.drop_index(op.f('ix_services_published_at'), table_name='services')
    op.drop_index('ix_services_published', table_name='services')
    op.drop_index(op.f('ix_services_is_featured'), table_name='services')
    op.drop_index(op.f('ix_services_is_active'), table_name='services')
    op.drop_index('ix_services_featured_active', table_name='services')
    op.drop_index('ix_services_category_active', table_name='services')
    op.drop_index(op.f('ix_services_category'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_blog_tags_slug'), table_name='blog_tags')
    op.drop_table('blog_tags')
    op.drop_index(op.f('ix_blog_categories_slug'), table_name='blog_categories')
    op.drop_table('blog_categories')
    # ### end Alembic commands ###
