"""Rename fiscal_code to tax_code in user_profiles

Revision ID: b2ffddf0cea5
Revises: b5ffb3369762
Create Date: 2026-01-16 17:29:08.456189+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2ffddf0cea5'
down_revision: Union[str, None] = 'b5ffb3369762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade database schema.
    Applica le modifiche al database per portarlo alla versione corrente.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_login_attempts_success', table_name='login_attempts')
    op.create_index('ix_login_attempts_success', 'login_attempts', ['success', 'attempted_at'], unique=False)
    op.drop_index('ix_service_content_service_id', table_name='service_content')
    op.create_index('ix_service_content_service_id', 'service_content', ['service_id'], unique=False)
    op.drop_index('ix_sessions_refresh_token', table_name='sessions')
    op.create_index(op.f('ix_sessions_refresh_token'), 'sessions', ['refresh_token'], unique=True)
    op.add_column('user_profiles', sa.Column('tax_code', sa.String(length=16), nullable=True, comment='Codice Fiscale italiano'))
    op.drop_column('user_profiles', 'fiscal_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade database schema.
    Reverte le modifiche per tornare alla versione precedente.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('fiscal_code', sa.VARCHAR(length=16), autoincrement=False, nullable=True, comment='Codice Fiscale italiano'))
    op.drop_column('user_profiles', 'tax_code')
    op.drop_index(op.f('ix_sessions_refresh_token'), table_name='sessions')
    op.create_index('ix_sessions_refresh_token', 'sessions', ['refresh_token'], unique=False)
    op.drop_index('ix_service_content_service_id', table_name='service_content')
    op.create_index('ix_service_content_service_id', 'service_content', ['service_id'], unique=True)
    op.drop_index('ix_login_attempts_success', table_name='login_attempts')
    op.create_index('ix_login_attempts_success', 'login_attempts', ['success'], unique=False)
    # ### end Alembic commands ###
