"""add files table for file storage

Revision ID: 0049e9562f20
Revises: 6480c43c0a5f
Create Date: 2026-01-15 17:53:21.123701+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0049e9562f20'
down_revision: Union[str, None] = '6480c43c0a5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade database schema.
    Applica le modifiche al database per portarlo alla versione corrente.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True, comment='FK a users (uploader)'),
    sa.Column('category', sa.Enum('INVOICE', 'DOCUMENT', 'IMAGE', 'AVATAR', 'ATTACHMENT', 'TEMP', name='filecategory'), nullable=False, comment='Categoria file (invoice, document, image, etc.)'),
    sa.Column('status', sa.Enum('UPLOADING', 'ACTIVE', 'DELETED', name='filestatus'), nullable=False, comment='Status file (uploading, active, deleted)'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='Nome file originale'),
    sa.Column('stored_filename', sa.String(length=255), nullable=False, comment='Nome file salvato (UUID + extension)'),
    sa.Column('file_path', sa.String(length=512), nullable=False, comment='Path relativo da UPLOAD_DIR (es: images/2026/01/uuid.jpg)'),
    sa.Column('mime_type', sa.String(length=100), nullable=False, comment='MIME type (image/jpeg, application/pdf, etc.)'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='Dimensione file in bytes'),
    sa.Column('file_extension', sa.String(length=10), nullable=True, comment='Estensione file (jpg, pdf, docx, etc.)'),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True, comment='SHA256 hash per integrity check'),
    sa.Column('is_public', sa.Boolean(), nullable=False, comment='File accessibile pubblicamente (senza auth)'),
    sa.Column('image_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Metadata immagine (width, height, format, etc.)'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Descrizione file (opzionale)'),
    sa.Column('reference_type', sa.String(length=50), nullable=True, comment='Tipo entità collegata (invoice, order, ticket, user)'),
    sa.Column('reference_id', sa.UUID(), nullable=True, comment='ID entità collegata'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp soft delete (NULL se attivo)'),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True, comment='FK a users (chi ha eliminato)'),
    sa.Column('download_count', sa.Integer(), nullable=False, comment='Contatore download'),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True, comment='Ultimo accesso file'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='File caricati e gestiti sul server locale'
    )
    op.create_index(op.f('ix_files_category'), 'files', ['category'], unique=False)
    op.create_index('ix_files_category_status', 'files', ['category', 'status'], unique=False)
    op.create_index('ix_files_deleted', 'files', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_files_deleted_at'), 'files', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_files_mime_type'), 'files', ['mime_type'], unique=False)
    op.create_index('ix_files_reference', 'files', ['reference_type', 'reference_id'], unique=False)
    op.create_index(op.f('ix_files_reference_id'), 'files', ['reference_id'], unique=False)
    op.create_index(op.f('ix_files_reference_type'), 'files', ['reference_type'], unique=False)
    op.create_index(op.f('ix_files_sha256_hash'), 'files', ['sha256_hash'], unique=False)
    op.create_index(op.f('ix_files_status'), 'files', ['status'], unique=False)
    op.create_index(op.f('ix_files_stored_filename'), 'files', ['stored_filename'], unique=True)
    op.create_index(op.f('ix_files_uploaded_by_id'), 'files', ['uploaded_by_id'], unique=False)
    op.create_index('ix_files_uploader_category', 'files', ['uploaded_by_id', 'category'], unique=False)
    # TODO: Uncomment when pgvector is installed
    # op.add_column('knowledge_base_chunks', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True, comment='Vector embedding per similarity search'))
    op.drop_index('ix_sessions_refresh_token', table_name='sessions')
    op.create_index(op.f('ix_sessions_refresh_token'), 'sessions', ['refresh_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade database schema.
    Reverte le modifiche per tornare alla versione precedente.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_refresh_token'), table_name='sessions')
    op.create_index('ix_sessions_refresh_token', 'sessions', ['refresh_token'], unique=False)
    # TODO: Uncomment when pgvector is installed
    # op.drop_column('knowledge_base_chunks', 'embedding')
    op.drop_index('ix_files_uploader_category', table_name='files')
    op.drop_index(op.f('ix_files_uploaded_by_id'), table_name='files')
    op.drop_index(op.f('ix_files_stored_filename'), table_name='files')
    op.drop_index(op.f('ix_files_status'), table_name='files')
    op.drop_index(op.f('ix_files_sha256_hash'), table_name='files')
    op.drop_index(op.f('ix_files_reference_type'), table_name='files')
    op.drop_index(op.f('ix_files_reference_id'), table_name='files')
    op.drop_index('ix_files_reference', table_name='files')
    op.drop_index(op.f('ix_files_mime_type'), table_name='files')
    op.drop_index(op.f('ix_files_deleted_at'), table_name='files')
    op.drop_index('ix_files_deleted', table_name='files')
    op.drop_index('ix_files_category_status', table_name='files')
    op.drop_index(op.f('ix_files_category'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
