"""Add system_logs table for real-time logging

Revision ID: 38db7eb912ca
Revises: 3aad2998b45d
Create Date: 2026-01-16 15:45:40.159977+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '38db7eb912ca'
down_revision: Union[str, None] = '3aad2998b45d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade database schema.
    Applica le modifiche al database per portarlo alla versione corrente.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consulting_packages', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment="Nome del pacchetto (es: 'Starter AI Compliance')",
               existing_nullable=False)
    op.alter_column('consulting_packages', 'slug',
               existing_type=sa.VARCHAR(length=255),
               comment='Slug URL-friendly per il pacchetto',
               existing_nullable=False)
    op.alter_column('consulting_packages', 'short_description',
               existing_type=sa.VARCHAR(length=500),
               comment='Descrizione breve per card/preview',
               existing_nullable=True)
    op.alter_column('consulting_packages', 'description',
               existing_type=sa.TEXT(),
               comment='Descrizione dettagliata del pacchetto',
               existing_nullable=True)
    op.alter_column('consulting_packages', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Prezzo fisso del pacchetto (EUR)',
               existing_nullable=False)
    op.alter_column('consulting_packages', 'original_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Prezzo originale prima dello sconto (opzionale)',
               existing_nullable=True)
    op.alter_column('consulting_packages', 'badge',
               existing_type=sa.VARCHAR(length=50),
               comment="Badge promozionale (es: 'PIÙ POPOLARE', 'BEST VALUE')",
               existing_nullable=True)
    op.alter_column('consulting_packages', 'badge_color',
               existing_type=sa.VARCHAR(length=50),
               comment="Colore del badge (es: 'primary', 'success', '#ff5733')",
               existing_nullable=True)
    op.alter_column('consulting_packages', 'features_json',
               existing_type=sa.TEXT(),
               comment='Features in formato JSON array',
               existing_nullable=True)
    op.alter_column('consulting_packages', 'duration_days',
               existing_type=sa.INTEGER(),
               comment='Durata del pacchetto in giorni (se applicabile)',
               existing_nullable=True)
    op.alter_column('consulting_packages', 'validity_info',
               existing_type=sa.VARCHAR(length=255),
               comment="Info validità (es: 'Valido 6 mesi dall\\'acquisto')",
               existing_nullable=True)
    op.alter_column('consulting_packages', 'cta_text',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               comment='Testo bottone call-to-action',
               existing_nullable=True)
    op.alter_column('consulting_packages', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Pacchetto visibile nel sito',
               existing_nullable=False)
    op.alter_column('consulting_packages', 'is_featured',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Pacchetto in evidenza (highlighted)',
               existing_nullable=False)
    op.alter_column('consulting_packages', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='Ordine di visualizzazione (0=primo)',
               existing_nullable=False)
    op.alter_column('consulting_packages', 'max_purchases',
               existing_type=sa.INTEGER(),
               comment='Numero massimo di acquisti disponibili (null=illimitato)',
               existing_nullable=True)
    op.alter_column('consulting_packages', 'purchased_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='Numero di volte che è stato acquistato',
               existing_nullable=False)
    op.alter_column('consulting_packages', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               comment='Primary key UUID',
               existing_nullable=False)
    op.alter_column('consulting_packages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               comment='Timestamp creazione record',
               existing_nullable=False)
    op.alter_column('consulting_packages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               comment='Timestamp ultimo aggiornamento',
               existing_nullable=False)
    op.drop_constraint('consulting_packages_slug_key', 'consulting_packages', type_='unique')
    op.drop_index('ix_consulting_packages_display_order', table_name='consulting_packages')
    op.drop_index('ix_consulting_packages_slug', table_name='consulting_packages')
    op.create_index(op.f('ix_consulting_packages_slug'), 'consulting_packages', ['slug'], unique=True)
    op.alter_column('homepage_banners', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment='Titolo principale',
               existing_nullable=False)
    op.alter_column('homepage_banners', 'subtitle',
               existing_type=sa.VARCHAR(length=255),
               comment='Sottotitolo',
               existing_nullable=True)
    op.alter_column('homepage_banners', 'description',
               existing_type=sa.TEXT(),
               comment='Descrizione dettagliata',
               existing_nullable=True)
    op.alter_column('homepage_banners', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               comment='URL immagine banner',
               existing_nullable=True)
    op.alter_column('homepage_banners', 'video_url',
               existing_type=sa.VARCHAR(length=500),
               comment='URL video (alternativa a immagine)',
               existing_nullable=True)
    op.alter_column('homepage_banners', 'cta_text',
               existing_type=sa.VARCHAR(length=100),
               comment='Testo bottone CTA',
               existing_nullable=True)
    op.alter_column('homepage_banners', 'cta_link',
               existing_type=sa.VARCHAR(length=500),
               comment='Link CTA',
               existing_nullable=True)
    op.alter_column('homepage_banners', 'cta_variant',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               comment='Variante bottone: primary, secondary, outline',
               existing_nullable=False)
    op.alter_column('homepage_banners', 'position',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               comment='Posizione: hero, slider, section, footer',
               existing_nullable=False)
    op.alter_column('homepage_banners', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='Ordine di visualizzazione (0=primo)',
               existing_nullable=False)
    op.alter_column('homepage_banners', 'background_color',
               existing_type=sa.VARCHAR(length=50),
               comment='Colore di sfondo (es: #ffffff, primary, muted)',
               existing_nullable=True)
    op.alter_column('homepage_banners', 'text_color',
               existing_type=sa.VARCHAR(length=50),
               comment='Colore del testo (es: #000000, white, foreground)',
               existing_nullable=True)
    op.alter_column('homepage_banners', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Banner visibile o nascosto',
               existing_nullable=False)
    op.alter_column('homepage_banners', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='Data inizio validità (opzionale)',
               existing_nullable=True)
    op.alter_column('homepage_banners', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='Data fine validità (opzionale)',
               existing_nullable=True)
    op.alter_column('homepage_banners', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               comment='Primary key UUID',
               existing_nullable=False)
    op.alter_column('homepage_banners', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               comment='Timestamp creazione record',
               existing_nullable=False)
    op.alter_column('homepage_banners', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               comment='Timestamp ultimo aggiornamento',
               existing_nullable=False)
    op.drop_index('ix_homepage_banners_created_at', table_name='homepage_banners')
    op.drop_index('ix_homepage_banners_display_order', table_name='homepage_banners')
    op.drop_index('ix_homepage_banners_is_active', table_name='homepage_banners')
    op.drop_index('ix_homepage_banners_position', table_name='homepage_banners')
    op.add_column('invoices', sa.Column('pdf_file_id', sa.UUID(), nullable=True, comment='FK a files (PDF fattura)'))
    op.add_column('invoices', sa.Column('xml_file_id', sa.UUID(), nullable=True, comment='FK a files (XML PA per SDI)'))
    op.alter_column('invoices', 'status',
               existing_type=postgresql.ENUM('draft', 'generated', 'sent', 'accepted', 'rejected', 'delivered', name='invoicestatus'),
               server_default=None,
               comment='Status fattura nel workflow',
               existing_nullable=False)
    op.alter_column('invoices', 'pdf_url',
               existing_type=sa.VARCHAR(length=500),
               comment='URL file PDF per cliente (legacy/deprecated)',
               existing_comment='URL file PDF per cliente',
               existing_nullable=True)
    op.alter_column('invoices', 'xml_url',
               existing_type=sa.VARCHAR(length=500),
               comment='URL file XML PA (legacy/deprecated)',
               existing_comment='URL file XML PA (per SDI)',
               existing_nullable=True)
    op.create_index(op.f('ix_invoices_pdf_file_id'), 'invoices', ['pdf_file_id'], unique=False)
    op.create_index(op.f('ix_invoices_xml_file_id'), 'invoices', ['xml_file_id'], unique=False)
    op.create_foreign_key(None, 'invoices', 'files', ['xml_file_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'invoices', 'files', ['pdf_file_id'], ['id'], ondelete='SET NULL')
    op.alter_column('knowledge_base_chunks', 'embedding',
               existing_type=sa.TEXT(),
               type_=pgvector.sqlalchemy.Vector(dim=1536),
               comment='Vector embedding per similarity search',
               existing_nullable=True)
    op.alter_column('knowledge_base_documents', 'document_type',
               existing_type=postgresql.ENUM('PDF', 'TEXT', 'URL', 'DOCX', 'MD', name='documenttype'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('knowledge_base_documents', 'file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('knowledge_base_documents', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Size in bytes')
    op.alter_column('knowledge_base_documents', 'chunk_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('knowledge_base_documents', 'processing_status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus'),
               server_default=None,
               existing_nullable=False)
    op.drop_column('knowledge_base_documents', 'file_type')
    op.drop_column('knowledge_base_documents', 'filename')
    op.drop_index('ix_login_attempts_success', table_name='login_attempts')
    op.create_index(op.f('ix_login_attempts_success'), 'login_attempts', ['success'], unique=False)
    op.drop_index('ix_package_services_package_id', table_name='package_services')
    op.drop_index('ix_package_services_service_id', table_name='package_services')
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade database schema.
    Reverte le modifiche per tornare alla versione precedente.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_package_services_service_id', 'package_services', ['service_id'], unique=False)
    op.create_index('ix_package_services_package_id', 'package_services', ['package_id'], unique=False)
    op.drop_index(op.f('ix_login_attempts_success'), table_name='login_attempts')
    op.create_index('ix_login_attempts_success', 'login_attempts', ['success', 'attempted_at'], unique=False)
    op.add_column('knowledge_base_documents', sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('knowledge_base_documents', sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='pdf, docx, txt, md'))
    op.alter_column('knowledge_base_documents', 'processing_status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus'),
               server_default=sa.text("'PENDING'::processingstatus"),
               existing_nullable=False)
    op.alter_column('knowledge_base_documents', 'chunk_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('knowledge_base_documents', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Size in bytes')
    op.alter_column('knowledge_base_documents', 'file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('knowledge_base_documents', 'document_type',
               existing_type=postgresql.ENUM('PDF', 'TEXT', 'URL', 'DOCX', 'MD', name='documenttype'),
               server_default=sa.text("'TEXT'::documenttype"),
               existing_nullable=False)
    op.alter_column('knowledge_base_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=1536),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='Vector embedding per similarity search',
               existing_nullable=True)
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_xml_file_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_pdf_file_id'), table_name='invoices')
    op.alter_column('invoices', 'xml_url',
               existing_type=sa.VARCHAR(length=500),
               comment='URL file XML PA (per SDI)',
               existing_comment='URL file XML PA (legacy/deprecated)',
               existing_nullable=True)
    op.alter_column('invoices', 'pdf_url',
               existing_type=sa.VARCHAR(length=500),
               comment='URL file PDF per cliente',
               existing_comment='URL file PDF per cliente (legacy/deprecated)',
               existing_nullable=True)
    op.alter_column('invoices', 'status',
               existing_type=postgresql.ENUM('draft', 'generated', 'sent', 'accepted', 'rejected', 'delivered', name='invoicestatus'),
               server_default=sa.text("'draft'::invoicestatus"),
               comment=None,
               existing_comment='Status fattura nel workflow',
               existing_nullable=False)
    op.drop_column('invoices', 'xml_file_id')
    op.drop_column('invoices', 'pdf_file_id')
    op.create_index('ix_homepage_banners_position', 'homepage_banners', ['position'], unique=False)
    op.create_index('ix_homepage_banners_is_active', 'homepage_banners', ['is_active'], unique=False)
    op.create_index('ix_homepage_banners_display_order', 'homepage_banners', ['display_order'], unique=False)
    op.create_index('ix_homepage_banners_created_at', 'homepage_banners', ['created_at'], unique=False)
    op.alter_column('homepage_banners', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp ultimo aggiornamento',
               existing_nullable=False)
    op.alter_column('homepage_banners', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp creazione record',
               existing_nullable=False)
    op.alter_column('homepage_banners', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               comment=None,
               existing_comment='Primary key UUID',
               existing_nullable=False)
    op.alter_column('homepage_banners', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Data fine validità (opzionale)',
               existing_nullable=True)
    op.alter_column('homepage_banners', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Data inizio validità (opzionale)',
               existing_nullable=True)
    op.alter_column('homepage_banners', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               comment=None,
               existing_comment='Banner visibile o nascosto',
               existing_nullable=False)
    op.alter_column('homepage_banners', 'text_color',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Colore del testo (es: #000000, white, foreground)',
               existing_nullable=True)
    op.alter_column('homepage_banners', 'background_color',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Colore di sfondo (es: #ffffff, primary, muted)',
               existing_nullable=True)
    op.alter_column('homepage_banners', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='Ordine di visualizzazione (0=primo)',
               existing_nullable=False)
    op.alter_column('homepage_banners', 'position',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'hero'::character varying"),
               comment=None,
               existing_comment='Posizione: hero, slider, section, footer',
               existing_nullable=False)
    op.alter_column('homepage_banners', 'cta_variant',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'primary'::character varying"),
               comment=None,
               existing_comment='Variante bottone: primary, secondary, outline',
               existing_nullable=False)
    op.alter_column('homepage_banners', 'cta_link',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Link CTA',
               existing_nullable=True)
    op.alter_column('homepage_banners', 'cta_text',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Testo bottone CTA',
               existing_nullable=True)
    op.alter_column('homepage_banners', 'video_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='URL video (alternativa a immagine)',
               existing_nullable=True)
    op.alter_column('homepage_banners', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='URL immagine banner',
               existing_nullable=True)
    op.alter_column('homepage_banners', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Descrizione dettagliata',
               existing_nullable=True)
    op.alter_column('homepage_banners', 'subtitle',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Sottotitolo',
               existing_nullable=True)
    op.alter_column('homepage_banners', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Titolo principale',
               existing_nullable=False)
    op.drop_index(op.f('ix_consulting_packages_slug'), table_name='consulting_packages')
    op.create_index('ix_consulting_packages_slug', 'consulting_packages', ['slug'], unique=False)
    op.create_index('ix_consulting_packages_display_order', 'consulting_packages', ['display_order'], unique=False)
    op.create_unique_constraint('consulting_packages_slug_key', 'consulting_packages', ['slug'])
    op.alter_column('consulting_packages', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp ultimo aggiornamento',
               existing_nullable=False)
    op.alter_column('consulting_packages', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp creazione record',
               existing_nullable=False)
    op.alter_column('consulting_packages', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               comment=None,
               existing_comment='Primary key UUID',
               existing_nullable=False)
    op.alter_column('consulting_packages', 'purchased_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='Numero di volte che è stato acquistato',
               existing_nullable=False)
    op.alter_column('consulting_packages', 'max_purchases',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Numero massimo di acquisti disponibili (null=illimitato)',
               existing_nullable=True)
    op.alter_column('consulting_packages', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='Ordine di visualizzazione (0=primo)',
               existing_nullable=False)
    op.alter_column('consulting_packages', 'is_featured',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='Pacchetto in evidenza (highlighted)',
               existing_nullable=False)
    op.alter_column('consulting_packages', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               comment=None,
               existing_comment='Pacchetto visibile nel sito',
               existing_nullable=False)
    op.alter_column('consulting_packages', 'cta_text',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'Acquista Ora'::character varying"),
               comment=None,
               existing_comment='Testo bottone call-to-action',
               existing_nullable=True)
    op.alter_column('consulting_packages', 'validity_info',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="Info validità (es: 'Valido 6 mesi dall\\'acquisto')",
               existing_nullable=True)
    op.alter_column('consulting_packages', 'duration_days',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Durata del pacchetto in giorni (se applicabile)',
               existing_nullable=True)
    op.alter_column('consulting_packages', 'features_json',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Features in formato JSON array',
               existing_nullable=True)
    op.alter_column('consulting_packages', 'badge_color',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Colore del badge (es: 'primary', 'success', '#ff5733')",
               existing_nullable=True)
    op.alter_column('consulting_packages', 'badge',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Badge promozionale (es: 'PIÙ POPOLARE', 'BEST VALUE')",
               existing_nullable=True)
    op.alter_column('consulting_packages', 'original_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Prezzo originale prima dello sconto (opzionale)',
               existing_nullable=True)
    op.alter_column('consulting_packages', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Prezzo fisso del pacchetto (EUR)',
               existing_nullable=False)
    op.alter_column('consulting_packages', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Descrizione dettagliata del pacchetto',
               existing_nullable=True)
    op.alter_column('consulting_packages', 'short_description',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Descrizione breve per card/preview',
               existing_nullable=True)
    op.alter_column('consulting_packages', 'slug',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Slug URL-friendly per il pacchetto',
               existing_nullable=False)
    op.alter_column('consulting_packages', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="Nome del pacchetto (es: 'Starter AI Compliance')",
               existing_nullable=False)
    # ### end Alembic commands ###
