"""Add account locking fields to users

Revision ID: c3f014d785a3
Revises: c960769efce7
Create Date: 2026-01-15 15:53:21.729123+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3f014d785a3'
down_revision: Union[str, None] = 'c960769efce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade database schema.
    Applica le modifiche al database per portarlo alla versione corrente.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    # TODO: Uncomment when pgvector is installed
    # op.add_column('knowledge_base_chunks', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True, comment='Vector embedding per similarity search'))
    op.drop_index('ix_login_attempts_success', table_name='login_attempts')
    op.create_index('ix_login_attempts_success', 'login_attempts', ['success', 'attempted_at'], unique=False)
    op.drop_index('ix_service_content_service_id', table_name='service_content')
    op.create_index('ix_service_content_service_id', 'service_content', ['service_id'], unique=False)
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0', comment='Contatore tentativi login falliti (reset a 0 dopo successo)'))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True, comment='Account bloccato fino a questo timestamp (NULL se non bloccato)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade database schema.
    Reverte le modifiche per tornare alla versione precedente.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_index('ix_service_content_service_id', table_name='service_content')
    op.create_index('ix_service_content_service_id', 'service_content', ['service_id'], unique=True)
    op.drop_index('ix_login_attempts_success', table_name='login_attempts')
    op.create_index('ix_login_attempts_success', 'login_attempts', ['success'], unique=False)
    op.drop_column('knowledge_base_chunks', 'embedding')
    # ### end Alembic commands ###
