"""Add homepage_banners table

Revision ID: 3aad2998b45d
Revises: 0049e9562f20
Create Date: 2026-01-16 09:45:39.984669+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aad2998b45d'
down_revision: Union[str, None] = '0049e9562f20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade database schema.
    Applica le modifiche al database per portarlo alla versione corrente.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homepage_banners',
    sa.Column('title', sa.String(length=255), nullable=False, comment='Titolo principale'),
    sa.Column('subtitle', sa.String(length=255), nullable=True, comment='Sottotitolo'),
    sa.Column('description', sa.Text(), nullable=True, comment='Descrizione dettagliata'),
    sa.Column('image_url', sa.String(length=500), nullable=True, comment='URL immagine banner'),
    sa.Column('video_url', sa.String(length=500), nullable=True, comment='URL video (alternativa a immagine)'),
    sa.Column('cta_text', sa.String(length=100), nullable=True, comment='Testo bottone CTA'),
    sa.Column('cta_link', sa.String(length=500), nullable=True, comment='Link CTA'),
    sa.Column('cta_variant', sa.String(length=50), nullable=False, comment='Variante bottone: primary, secondary, outline'),
    sa.Column('position', sa.String(length=50), nullable=False, comment='Posizione: hero, slider, section, footer'),
    sa.Column('display_order', sa.Integer(), nullable=False, comment='Ordine di visualizzazione (0=primo)'),
    sa.Column('background_color', sa.String(length=50), nullable=True, comment='Colore di sfondo (es: #ffffff, primary, muted)'),
    sa.Column('text_color', sa.String(length=50), nullable=True, comment='Colore del testo (es: #000000, white, foreground)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Banner visibile o nascosto'),
    sa.Column('start_date', sa.DateTime(), nullable=True, comment='Data inizio validità (opzionale)'),
    sa.Column('end_date', sa.DateTime(), nullable=True, comment='Data fine validità (opzionale)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('invoices', sa.Column('status', sa.Enum('DRAFT', 'GENERATED', 'SENT', 'ACCEPTED', 'REJECTED', 'DELIVERED', name='invoicestatus'), nullable=False, comment='Status fattura nel workflow'))
    op.add_column('invoices', sa.Column('pdf_file_id', sa.UUID(), nullable=True, comment='FK a files (PDF fattura)'))
    op.add_column('invoices', sa.Column('xml_file_id', sa.UUID(), nullable=True, comment='FK a files (XML PA per SDI)'))
    op.alter_column('invoices', 'pdf_url',
               existing_type=sa.VARCHAR(length=500),
               comment='URL file PDF per cliente (legacy/deprecated)',
               existing_comment='URL file PDF per cliente',
               existing_nullable=True)
    op.alter_column('invoices', 'xml_url',
               existing_type=sa.VARCHAR(length=500),
               comment='URL file XML PA (legacy/deprecated)',
               existing_comment='URL file XML PA (per SDI)',
               existing_nullable=True)
    op.create_index(op.f('ix_invoices_pdf_file_id'), 'invoices', ['pdf_file_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_xml_file_id'), 'invoices', ['xml_file_id'], unique=False)
    op.create_foreign_key(None, 'invoices', 'files', ['xml_file_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'invoices', 'files', ['pdf_file_id'], ['id'], ondelete='SET NULL')
    op.add_column('knowledge_base_chunks', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True, comment='Vector embedding per similarity search'))
    op.add_column('knowledge_base_documents', sa.Column('document_type', sa.Enum('PDF', 'TEXT', 'URL', 'DOCX', 'MD', name='documenttype'), nullable=False))
    op.add_column('knowledge_base_documents', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('knowledge_base_documents', sa.Column('source_url', sa.String(length=500), nullable=True))
    op.add_column('knowledge_base_documents', sa.Column('author', sa.String(length=100), nullable=True))
    op.add_column('knowledge_base_documents', sa.Column('chunk_count', sa.Integer(), nullable=False))
    op.add_column('knowledge_base_documents', sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus'), nullable=False))
    op.add_column('knowledge_base_documents', sa.Column('processed_at', sa.DateTime(), nullable=True))
    op.add_column('knowledge_base_documents', sa.Column('uploaded_by_user_id', sa.UUID(), nullable=False))
    op.alter_column('knowledge_base_documents', 'file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('knowledge_base_documents', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Size in bytes')
    op.drop_constraint('knowledge_base_documents_uploaded_by_fkey', 'knowledge_base_documents', type_='foreignkey')
    op.create_foreign_key(None, 'knowledge_base_documents', 'users', ['uploaded_by_user_id'], ['id'])
    op.drop_column('knowledge_base_documents', 'uploaded_by')
    op.drop_column('knowledge_base_documents', 'file_type')
    op.drop_column('knowledge_base_documents', 'filename')
    op.drop_index('ix_sessions_refresh_token', table_name='sessions')
    op.create_index('ix_sessions_refresh_token', 'sessions', ['refresh_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade database schema.
    Reverte le modifiche per tornare alla versione precedente.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sessions_refresh_token', table_name='sessions')
    op.create_index('ix_sessions_refresh_token', 'sessions', ['refresh_token'], unique=True)
    op.add_column('knowledge_base_documents', sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('knowledge_base_documents', sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='pdf, docx, txt, md'))
    op.add_column('knowledge_base_documents', sa.Column('uploaded_by', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'knowledge_base_documents', type_='foreignkey')
    op.create_foreign_key('knowledge_base_documents_uploaded_by_fkey', 'knowledge_base_documents', 'users', ['uploaded_by'], ['id'])
    op.alter_column('knowledge_base_documents', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Size in bytes')
    op.alter_column('knowledge_base_documents', 'file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('knowledge_base_documents', 'uploaded_by_user_id')
    op.drop_column('knowledge_base_documents', 'processed_at')
    op.drop_column('knowledge_base_documents', 'processing_status')
    op.drop_column('knowledge_base_documents', 'chunk_count')
    op.drop_column('knowledge_base_documents', 'author')
    op.drop_column('knowledge_base_documents', 'source_url')
    op.drop_column('knowledge_base_documents', 'description')
    op.drop_column('knowledge_base_documents', 'document_type')
    op.drop_column('knowledge_base_chunks', 'embedding')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_xml_file_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_pdf_file_id'), table_name='invoices')
    op.alter_column('invoices', 'xml_url',
               existing_type=sa.VARCHAR(length=500),
               comment='URL file XML PA (per SDI)',
               existing_comment='URL file XML PA (legacy/deprecated)',
               existing_nullable=True)
    op.alter_column('invoices', 'pdf_url',
               existing_type=sa.VARCHAR(length=500),
               comment='URL file PDF per cliente',
               existing_comment='URL file PDF per cliente (legacy/deprecated)',
               existing_nullable=True)
    op.drop_column('invoices', 'xml_file_id')
    op.drop_column('invoices', 'pdf_file_id')
    op.drop_column('invoices', 'status')
    op.drop_table('homepage_banners')
    # ### end Alembic commands ###
