"""add_newsletter_sent_to_blog_posts

Revision ID: b1128fd6a7c2
Revises: 97bba8d62ea1
Create Date: 2026-01-16 19:04:02.876890+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1128fd6a7c2'
down_revision: Union[str, None] = '97bba8d62ea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade database schema.
    Applica le modifiche al database per portarlo alla versione corrente.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_posts', sa.Column('newsletter_sent', sa.Boolean(), nullable=False, comment="True se l'articolo è stato inviato via newsletter"))
    op.add_column('blog_posts', sa.Column('newsletter_sent_at', sa.DateTime(timezone=True), nullable=True, comment='Data invio newsletter'))
    op.drop_index('ix_login_attempts_success', table_name='login_attempts')
    op.create_index('ix_login_attempts_success', 'login_attempts', ['success', 'attempted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade database schema.
    Reverte le modifiche per tornare alla versione precedente.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_login_attempts_success', table_name='login_attempts')
    op.create_index('ix_login_attempts_success', 'login_attempts', ['success'], unique=False)
    op.drop_column('blog_posts', 'newsletter_sent_at')
    op.drop_column('blog_posts', 'newsletter_sent')
    # ### end Alembic commands ###
