"""add_about_page_tables

Revision ID: 97bba8d62ea1
Revises: 4f7156a2742e
Create Date: 2026-01-16 18:49:37.917740+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97bba8d62ea1'
down_revision: Union[str, None] = '4f7156a2742e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade database schema.
    Applica le modifiche al database per portarlo alla versione corrente.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_pages',
    sa.Column('profile_name', sa.String(length=255), nullable=False),
    sa.Column('profile_title', sa.String(length=255), nullable=False),
    sa.Column('profile_description', sa.Text(), nullable=False),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('profile_badges', sa.JSON(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competence_sections',
    sa.Column('about_page_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.ForeignKeyConstraint(['about_page_id'], ['about_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specialization_areas',
    sa.Column('about_page_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.ForeignKeyConstraint(['about_page_id'], ['about_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade database schema.
    Reverte le modifiche per tornare alla versione precedente.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specialization_areas')
    op.drop_table('competence_sections')
    op.drop_table('about_pages')
    # ### end Alembic commands ###
