"""add_use_cases_table

Revision ID: 4f7156a2742e
Revises: de32520f7dc0
Create Date: 2026-01-16 18:22:46.664492+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f7156a2742e'
down_revision: Union[str, None] = 'de32520f7dc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade database schema.
    Applica le modifiche al database per portarlo alla versione corrente.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('use_cases',
    sa.Column('title', sa.String(length=255), nullable=False, comment="Titolo caso d'uso (es: 'Fintech: AI Credit Scoring Compliance')"),
    sa.Column('slug', sa.String(length=255), nullable=False, comment='Slug URL-friendly per SEO'),
    sa.Column('industry', sa.String(length=100), nullable=False, comment="Settore/Categoria (es: 'Finance', 'Sanità', 'Retail', 'Industria 4.0')"),
    sa.Column('icon', sa.String(length=255), nullable=True, comment='Nome icona Lucide o URL immagine'),
    sa.Column('challenge_title', sa.String(length=255), nullable=False, comment='Titolo sezione sfida'),
    sa.Column('challenge_description', sa.Text(), nullable=False, comment='Descrizione del problema/sfida del cliente'),
    sa.Column('solution_title', sa.String(length=255), nullable=False, comment='Titolo sezione soluzione'),
    sa.Column('solution_description', sa.Text(), nullable=False, comment='Descrizione della soluzione implementata'),
    sa.Column('result_title', sa.String(length=255), nullable=False, comment='Titolo sezione risultato'),
    sa.Column('result_description', sa.Text(), nullable=False, comment="Descrizione dell'outcome/risultato ottenuto"),
    sa.Column('display_order', sa.Integer(), nullable=False, comment='Ordine di visualizzazione (0 = primo)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Se attivo e visibile pubblicamente'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp creazione record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp ultimo aggiornamento'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_use_cases_industry'), 'use_cases', ['industry'], unique=False)
    op.create_index(op.f('ix_use_cases_is_active'), 'use_cases', ['is_active'], unique=False)
    op.create_index(op.f('ix_use_cases_slug'), 'use_cases', ['slug'], unique=True)
    op.drop_index('ix_login_attempts_success', table_name='login_attempts')
    op.create_index(op.f('ix_login_attempts_success'), 'login_attempts', ['success'], unique=False)
    op.drop_index('ix_service_content_service_id', table_name='service_content')
    op.create_index(op.f('ix_service_content_service_id'), 'service_content', ['service_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade database schema.
    Reverte le modifiche per tornare alla versione precedente.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_content_service_id'), table_name='service_content')
    op.create_index('ix_service_content_service_id', 'service_content', ['service_id'], unique=False)
    op.drop_index(op.f('ix_login_attempts_success'), table_name='login_attempts')
    op.create_index('ix_login_attempts_success', 'login_attempts', ['success', 'attempted_at'], unique=False)
    op.drop_index(op.f('ix_use_cases_slug'), table_name='use_cases')
    op.drop_index(op.f('ix_use_cases_is_active'), table_name='use_cases')
    op.drop_index(op.f('ix_use_cases_industry'), table_name='use_cases')
    op.drop_table('use_cases')
    # ### end Alembic commands ###
