"""Add company fields to user profile

Revision ID: b5ffb3369762
Revises: 38db7eb912ca
Create Date: 2026-01-16 17:26:18.173302+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5ffb3369762'
down_revision: Union[str, None] = '38db7eb912ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade database schema.
    Applica le modifiche al database per portarlo alla versione corrente.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'action',
               existing_type=postgresql.ENUM('LOGIN', 'LOGOUT', 'CREATE', 'READ', 'UPDATE', 'DELETE', 'EXPORT', 'IMPORT', name='auditaction'),
               type_=sa.Enum('LOGIN', 'LOGOUT', 'CREATE', 'READ', 'UPDATE', 'DELETE', 'EXPORT', 'IMPORT', name='auditaction', native_enum=False),
               existing_comment='Tipo azione eseguita',
               existing_nullable=False)
    op.drop_index('knowledge_base_chunks_embedding_idx', table_name='knowledge_base_chunks', postgresql_using='hnsw')
    op.drop_index('ix_sessions_refresh_token', table_name='sessions')
    op.create_index('ix_sessions_refresh_token', 'sessions', ['refresh_token'], unique=False)
    op.alter_column('system_logs', 'level',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='loglevel', native_enum=False),
               existing_nullable=False)
    op.alter_column('system_logs', 'module',
               existing_type=sa.VARCHAR(length=100),
               comment='auth, payment, email, cms, api, etc.',
               existing_nullable=False)
    op.alter_column('system_logs', 'context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Extra metadata',
               existing_nullable=True)
    op.alter_column('system_logs', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               comment='Primary key UUID',
               existing_nullable=False)
    op.create_table_comment(
        'system_logs',
        'Log applicazione sistema',
        existing_comment=None,
        schema=None
    )
    op.add_column('user_profiles', sa.Column('phone_mobile', sa.String(length=20), nullable=True, comment='Telefono mobile/cellulare'))
    op.add_column('user_profiles', sa.Column('phone_landline', sa.String(length=20), nullable=True, comment='Telefono fisso'))
    op.add_column('user_profiles', sa.Column('rea_number', sa.String(length=50), nullable=True, comment='Numero REA (Repertorio Economico Amministrativo, es: MI-1234567)'))
    op.add_column('user_profiles', sa.Column('legal_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Indirizzo sede legale (JSON: street, city, zip, province, country)'))
    op.add_column('user_profiles', sa.Column('operational_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Indirizzo sede operativa (JSON: street, city, zip, province, country)'))
    op.alter_column('user_profiles', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='Telefono (deprecated - usare phone_mobile o phone_landline)',
               existing_comment='Telefono (formato internazionale)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade database schema.
    Reverte le modifiche per tornare alla versione precedente.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='Telefono (formato internazionale)',
               existing_comment='Telefono (deprecated - usare phone_mobile o phone_landline)',
               existing_nullable=True)
    op.drop_column('user_profiles', 'operational_address')
    op.drop_column('user_profiles', 'legal_address')
    op.drop_column('user_profiles', 'rea_number')
    op.drop_column('user_profiles', 'phone_landline')
    op.drop_column('user_profiles', 'phone_mobile')
    op.drop_table_comment(
        'system_logs',
        existing_comment='Log applicazione sistema',
        schema=None
    )
    op.alter_column('system_logs', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               comment=None,
               existing_comment='Primary key UUID',
               existing_nullable=False)
    op.alter_column('system_logs', 'context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Extra metadata',
               existing_nullable=True)
    op.alter_column('system_logs', 'module',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='auth, payment, email, cms, api, etc.',
               existing_nullable=False)
    op.alter_column('system_logs', 'level',
               existing_type=sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='loglevel', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_index('ix_sessions_refresh_token', table_name='sessions')
    op.create_index('ix_sessions_refresh_token', 'sessions', ['refresh_token'], unique=True)
    op.create_index('knowledge_base_chunks_embedding_idx', 'knowledge_base_chunks', ['embedding'], unique=False, postgresql_using='hnsw')
    op.alter_column('audit_logs', 'action',
               existing_type=sa.Enum('LOGIN', 'LOGOUT', 'CREATE', 'READ', 'UPDATE', 'DELETE', 'EXPORT', 'IMPORT', name='auditaction', native_enum=False),
               type_=postgresql.ENUM('LOGIN', 'LOGOUT', 'CREATE', 'READ', 'UPDATE', 'DELETE', 'EXPORT', 'IMPORT', name='auditaction'),
               existing_comment='Tipo azione eseguita',
               existing_nullable=False)
    # ### end Alembic commands ###
