"""Make ip_address nullable in login_attempts

Revision ID: 6480c43c0a5f
Revises: c3f014d785a3
Create Date: 2026-01-15 16:00:16.910948+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6480c43c0a5f'
down_revision: Union[str, None] = 'c3f014d785a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade database schema.
    Applica le modifiche al database per portarlo alla versione corrente.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    # TODO: Uncomment when pgvector is installed
    # op.add_column('knowledge_base_chunks', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True, comment='Vector embedding per similarity search'))
    op.alter_column('login_attempts', 'ip_address',
               existing_type=postgresql.INET(),
               nullable=True,
               existing_comment='IP address tentativo')
    op.drop_index('ix_login_attempts_success', table_name='login_attempts')
    op.create_index(op.f('ix_login_attempts_success'), 'login_attempts', ['success'], unique=False)
    op.drop_index('ix_service_content_service_id', table_name='service_content')
    op.create_index(op.f('ix_service_content_service_id'), 'service_content', ['service_id'], unique=True)
    op.alter_column('users', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_comment='Contatore tentativi login falliti (reset a 0 dopo successo)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade database schema.
    Reverte le modifiche per tornare alla versione precedente.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_comment='Contatore tentativi login falliti (reset a 0 dopo successo)',
               existing_nullable=False)
    op.drop_index(op.f('ix_service_content_service_id'), table_name='service_content')
    op.create_index('ix_service_content_service_id', 'service_content', ['service_id'], unique=False)
    op.drop_index(op.f('ix_login_attempts_success'), table_name='login_attempts')
    op.create_index('ix_login_attempts_success', 'login_attempts', ['success', 'attempted_at'], unique=False)
    op.alter_column('login_attempts', 'ip_address',
               existing_type=postgresql.INET(),
               nullable=False,
               existing_comment='IP address tentativo')
    # TODO: Uncomment when pgvector is installed
    # op.drop_column('knowledge_base_chunks', 'embedding')
    # ### end Alembic commands ###
